/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { JobApplicationService } from "../jobApplication.service";
import { JobApplicationCreateInput } from "./JobApplicationCreateInput";
import { JobApplication } from "./JobApplication";
import { JobApplicationFindManyArgs } from "./JobApplicationFindManyArgs";
import { JobApplicationWhereUniqueInput } from "./JobApplicationWhereUniqueInput";
import { JobApplicationUpdateInput } from "./JobApplicationUpdateInput";
import { InterviewFindManyArgs } from "../../interview/base/InterviewFindManyArgs";
import { Interview } from "../../interview/base/Interview";
import { InterviewWhereUniqueInput } from "../../interview/base/InterviewWhereUniqueInput";

export class JobApplicationControllerBase {
  constructor(protected readonly service: JobApplicationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JobApplication })
  async createJobApplication(
    @common.Body() data: JobApplicationCreateInput
  ): Promise<JobApplication> {
    return await this.service.createJobApplication({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        requirements: true,
        location: true,
        jobTitle: true,
        company: true,
        description: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [JobApplication] })
  @ApiNestedQuery(JobApplicationFindManyArgs)
  async jobApplications(
    @common.Req() request: Request
  ): Promise<JobApplication[]> {
    const args = plainToClass(JobApplicationFindManyArgs, request.query);
    return this.service.jobApplications({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        requirements: true,
        location: true,
        jobTitle: true,
        company: true,
        description: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JobApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async jobApplication(
    @common.Param() params: JobApplicationWhereUniqueInput
  ): Promise<JobApplication | null> {
    const result = await this.service.jobApplication({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        requirements: true,
        location: true,
        jobTitle: true,
        company: true,
        description: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JobApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateJobApplication(
    @common.Param() params: JobApplicationWhereUniqueInput,
    @common.Body() data: JobApplicationUpdateInput
  ): Promise<JobApplication | null> {
    try {
      return await this.service.updateJobApplication({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          requirements: true,
          location: true,
          jobTitle: true,
          company: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JobApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteJobApplication(
    @common.Param() params: JobApplicationWhereUniqueInput
  ): Promise<JobApplication | null> {
    try {
      return await this.service.deleteJobApplication({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          requirements: true,
          location: true,
          jobTitle: true,
          company: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/interviews")
  @ApiNestedQuery(InterviewFindManyArgs)
  async findInterviews(
    @common.Req() request: Request,
    @common.Param() params: JobApplicationWhereUniqueInput
  ): Promise<Interview[]> {
    const query = plainToClass(InterviewFindManyArgs, request.query);
    const results = await this.service.findInterviews(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        interviewDate: true,

        resume: {
          select: {
            id: true,
          },
        },

        jobApplication: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/interviews")
  async connectInterviews(
    @common.Param() params: JobApplicationWhereUniqueInput,
    @common.Body() body: InterviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interviews: {
        connect: body,
      },
    };
    await this.service.updateJobApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/interviews")
  async updateInterviews(
    @common.Param() params: JobApplicationWhereUniqueInput,
    @common.Body() body: InterviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interviews: {
        set: body,
      },
    };
    await this.service.updateJobApplication({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/interviews")
  async disconnectInterviews(
    @common.Param() params: JobApplicationWhereUniqueInput,
    @common.Body() body: InterviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interviews: {
        disconnect: body,
      },
    };
    await this.service.updateJobApplication({
      where: params,
      data,
      select: { id: true },
    });
  }
}
